version: '3'
services:

  postgreDB:
    container_name: postgreDB_container
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stuffer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
    volumes:
      - postgre_data:/var/lib/postgresql/data
    networks:
      - stuffer_network

volumes:
  postgre_data:

networks:
  stuffer_network:
    external: true