version: '3'
services:

  nginx:
    container_name: nginx_container
    image: "nginx:alpine"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./www:/www/data:ro
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true