version: '2'
services:

  nginx:
    container_name: nginx_container
    image: "nginx:alpine"
    ports:
      - "80:80"
    volumes:
      - ./conf/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - stuffer

  stuffer:
    container_name: stuffer_container
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
    depends_on:
      - postgreDB

  postgreDB:
    container_name: postgreDB_container
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stuffer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
    volumes:
      - data_volume:/var/lib/postgresql/data
#      - /home/iwaneez/postgreData:/var/lib/postgresql/data

volumes:
  data_volume: